name: citizen_budget_lab
version: 1.0.0
config-version: 2

profile: cbl

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  citizen_budget_lab:
    +materialized: view
    staging:
      +schema: staging
    dim:
      +schema: dim
    fact:
      +schema: fact
    vw:
      +schema: vw

seeds:
  citizen-budget-lab:
    mapping_state_to_cofog:
      +column_types:
        source: varchar
        year: integer
        mission_code: varchar
        programme_code: varchar
        cofog_code: varchar
        weight: double

vars:
  'dbt_date:time_zone': 'UTC'
  state_budget_sample: 'data/sample_state_budget.csv'
  state_budget_glob: 'data/cache/state_budget_mission_*.csv'
  procurement_sample: 'data/sample_procurement.csv'
  procurement_glob: 'data/cache/procurement_contracts_*.csv'
  lego_pieces_json: 'data/lego_pieces.json'
  lego_baseline_glob: 'data/cache/lego_baseline_*.json'
  gdp_series_csv: 'data/gdp_series.csv'
  baseline_deficit_debt_csv: 'data/baseline_deficit_debt.csv'
