version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    image: citizen-budget-lab/api:dev
    environment:
      # Pass through optional secrets and HTTP cache tuning from host/.env
      INSEE_CLIENT_ID: ${INSEE_CLIENT_ID:-}
      INSEE_CLIENT_SECRET: ${INSEE_CLIENT_SECRET:-}
      HTTP_CACHE_ENABLED: ${HTTP_CACHE_ENABLED:-1}
      HTTP_CACHE_TTL_DEFAULT: ${HTTP_CACHE_TTL_DEFAULT:-86400}
      HTTP_CACHE_TTL_INSEE: ${HTTP_CACHE_TTL_INSEE:-21600}
      HTTP_CACHE_TTL_EUROSTAT: ${HTTP_CACHE_TTL_EUROSTAT:-86400}
      HTTP_CACHE_TTL_DATAGOUV: ${HTTP_CACHE_TTL_DATAGOUV:-86400}
      HTTP_CACHE_TTL_GEO: ${HTTP_CACHE_TTL_GEO:-604800}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build-time injection for Next.js client to call API by service name
        NEXT_PUBLIC_GRAPHQL_URL: http://api:8000/graphql
    image: citizen-budget-lab/frontend:dev
    depends_on:
      - api
    ports:
      - "3000:3000"

