version: 2

models:
  - name: stg_state_budget_lines
    description: Raw state budget lines (central, mission/programme level) from warmed CSVs + sample
    columns:
      - name: year
        tests: [not_null]
      - name: mission_code
        tests: [not_null]
      - name: cp_eur
        tests: [not_null]
      - name: ae_eur
        tests: [not_null]

  - name: stg_procurement_contracts
    description: Raw procurement contracts from warmed CSVs + sample
    columns:
      - name: contract_id
        tests: [not_null]
      - name: supplier_siren
        tests: [not_null]
      - name: amount_eur
        tests: [not_null]

  - name: stg_plf_2026_plafonds
    description: Mission-level PLF 2026 spending ceilings sourced from the cache warmer output.
    columns:
      - name: year
        tests: [not_null]
      - name: mission_code
        tests: [not_null]
      - name: plafond_eur
        tests: [not_null]

  - name: dim_cofog_mapping
    description: Mapping admin codes to COFOG functions with weights
    tests:
      - dbt_utils.expression_is_true:
          expression: "weight >= 0 and weight <= 1"
    columns:
      - name: source_type
        tests: [not_null]
      - name: programme_code
      - name: cofog_code
        tests: [not_null]
      - name: weight
        tests:
          - not_null

  - name: dim_lego_pieces
    description: LEGO pieces definitions
    columns:
      - name: piece_id
        tests: [not_null, unique]

  - name: fct_admin_by_mission
    description: Aggregates by mission and year for AE/CP
    columns:
      - name: year
        tests: [not_null]
      - name: mission_code
        tests: [not_null]
      - name: apu_subsector
        tests:
          - not_null
          - accepted_values:
              values: ['APUC', 'APUL', 'ASSO']

  - name: fct_admin_by_cofog
    description: Aggregates by COFOG major using weighted mapping
    columns:
      - name: year
        tests: [not_null]
      - name: cofog_code
        tests: [not_null]

  - name: fct_simulation_baseline_2026
    description: |
      Mission-level simulation baseline for PLF 2026.
      - Starts from enacted 2025 mission CP totals (`fct_admin_by_mission`).
      - Overlays PLF 2026 spending ceilings parsed from the official XLS workbook (`stg_plf_2026_plafonds`).
      - Applies aggregate revenue adjustments derived from consensus macro forecasts (`macro_forecasts_2026`) by
        scaling the 2026 revenue slice of the LEGO baseline (`fct_lego_baseline`).
      - Revenue adjustments are allocated back to missions in proportion to their 2025 CP weight to estimate the
        net fiscal space at constant policy.
    columns:
      - name: mission_code
        tests: [not_null]
      - name: plf_2026_ceiling_eur
        tests: [not_null]
      - name: revenue_adjustment_eur
        tests: [not_null]

  - name: fct_lego_baseline
    description: LEGO pieces baseline amounts and shares
    columns:
      - name: year
        tests: [not_null]
      - name: piece_id
        tests: [not_null]

  - name: fct_procurement_suppliers
    description: Supplier-level procurement rollups by year with competition flags
    columns:
      - name: year
        tests: [not_null]
      - name: supplier_siren
        tests: [not_null]

  - name: dim_apu_entities
    description: Classification of administrative and procurement identifiers into APU subsectors.
    columns:
      - name: domain
        tests: [not_null]
      - name: key_type
        tests: [not_null]
      - name: key_value
        tests: [not_null]
      - name: apu_subsector
        tests:
          - not_null
          - accepted_values:
              values: ['APUC', 'APUL', 'ASSO']

  - name: dim_apu_subsector
    description: Reference table for APU subsectors with labels and descriptions.
    columns:
      - name: apu_subsector
        tests: [not_null, unique]

  - name: fct_admin_by_apu
    description: Aggregated administrative spending by APU subsector
    columns:
      - name: year
        tests: [not_null]
      - name: apu_subsector
        tests:
          - not_null
          - accepted_values:
              values: ['APUC', 'APUL', 'ASSO']

  - name: fct_procurement_by_apu
    description: Procurement aggregates by buyer APU subsector
    columns:
      - name: year
        tests: [not_null]
      - name: apu_subsector
        tests:
          - not_null
          - accepted_values:
              values: ['APUC', 'APUL', 'ASSO']

  - name: stg_macro_gdp
    description: Staging GDP series (EUR) by year from warmed CSV
    columns:
      - name: year
        tests: [not_null]
      - name: gdp_eur
        tests: [not_null]

  - name: stg_baseline_def_debt
    description: Staging baseline deficit and debt (EUR) by year from warmed CSV
    columns:
      - name: year
        tests: [not_null]
      - name: deficit_eur
        tests: [not_null]
      - name: debt_eur
        tests: [not_null]

  - name: dim_macro_gdp
    description: GDP series (EUR) by year
    columns:
      - name: year
        tests: [not_null]
      - name: gdp_eur
        tests: [not_null]

  - name: fct_baseline_deficit_debt
    description: Baseline deficit and debt (EUR) by year
    columns:
      - name: year
        tests: [not_null]
      - name: deficit_eur
        tests: [not_null]
      - name: debt_eur
        tests: [not_null]


seeds:
  - name: mapping_state_to_cofog
    description: Seed generated from data/cofog_mapping.json, mapping admin codes to COFOG.
    columns:
      - name: source
        tests: [not_null, accepted_values: { values: ['mission', 'programme', 'programme_year'] }]
      - name: year
        description: The year the mapping is effective for (null means default).
      - name: mission_code
      - name: programme_code
      - name: cofog_code
        tests: [not_null]
      - name: weight
        tests: [not_null]

  - name: plf_2026_plafonds
    description: Reference PLF 2026 mission ceilings used for development and tests (millions converted to euros).
    columns:
      - name: year
        tests: [not_null]
      - name: mission_code
        tests: [not_null]
      - name: plf_ceiling_eur
        tests: [not_null]

  - name: macro_forecasts_2026
    description: Consensus macroeconomic parameters (growth, inflation, unemployment) underpinning PLF 2026 baseline adjustments.
    columns:
      - name: year
        tests: [not_null]
      - name: gdp_growth_pct
        tests: [not_null]
      - name: inflation_pct
        tests: [not_null]
      - name: unemployment_rate_pct
        tests: [not_null]
